bookings/urls.py
from django.urls import path
from .views import BookingListView, GalleryListView

app_name="bookings"


urlpatterns = [
  path("", BookingListView.as_view(), name="home"),
  path("gallery/<str:category>/", GalleryListView.as_view(), name="gallery"),
  path("gallery/", GalleryListView.as_view(), name="gallery_all"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", HomeView.as_view(), name="home" ),
    path("bookings/", include("bookings.urls", namespace="bookings")),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookings/models.py
from django.db import models


class Username(models.Model):
    username = models.CharField(max_length=100)
    cellphone = models.CharField(max_length=20)
    email = models.CharField(max_length=100, blank =True)
    address = models.CharField(max_length=100, blank =True)

    def __str__(self):
        return self.username

class Category(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='category_images/', blank=True, null=True)

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(blank =True, null=True)
    author = models.CharField(max_length=100, blank =True, null=True)
    publication_year = models.PositiveIntegerField(blank =True, null=True)
    image = models.ImageField(upload_to='book_images/', blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='books', blank=True, null=True)

    def __str__(self):
        return self.title

class Rental(models.Model):
    user = models.ForeignKey(Username, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    return_date = models.DateField(null=True, blank=True)
    STATUS_CHOICES = (
        ('pending', 'pending'),
        ('returned', 'returned'),
    )
    status = models.CharField(max_length=10, choices=STATUS_CHOICES)

    def __str__(self):
        return f"{self.user.username} rented {self.book.title}"

    def __str__(self):
        return self.user.username

bookings/views.py
from django.shortcuts import render
from django.views.generic import View
from .models import Book, Category

class BookingListView(View):
  def get(self, request, *args, **kwargs):
    books = Book.objects.all()
    context = {
      'books': books,
    }
    return render(request, "bookings/bookings.html", context)

class GalleryListView(View):
  def get(self, request, category=None, *args, **kwargs):

    books = Book.objects.all()
    categories = Category.objects.all()[:6]
    category_name = None

    if category:
      books = books.filter(category__name__iexact=category)
      category_name = Category.objects.get(name__iexact=category).name

    context = {
      'books': books,
      'categories': categories,
      'category_name': category_name
    }

    template = "bookings/gallery_all.html"

    if category:
      template = "bookings/gallery.html"

    return render(request, template, context)

core/views.py
from django.views.generic import View
from django.shortcuts import render, redirect
from bookings.models import Category

class HomeView(View):
  def get(self, request, *args, **kwargs):
    categories = Category.objects.all()[:6]
    context = {
      'categories': categories
    }
    return render(request, "home/home.html", context)

templates/bookings/bookings.html
{% extends "index.html" %}

  {% block title %}Books{% endblock title %}
  {% block content %}

  <div class="py-8 px-4 w-fit mx-auto">
    <h2 class="text-4xl">Explore our books</h2>
  </div>
  <div class="flex flex-wrap justify-center items-center gap-4 p-8">

    {% for book in books %}
      <div class="flex flex-col items-center bg-white rounded-lg shadow w-full md:flex-row md:max-w-xl hover:bg-zinc-50">

        {% if book.image %}
          <img src="{{ book.image.url }}" class="object-cover w-full rounded-t-lg h-96 md:h-auto md:w-48 md:rounded-none md:rounded-s-lg" alt="">
        {% endif %}

        <div class="flex flex-col justify-between p-4 w-full">
          {% if book.title %}
            <h3 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 uppercase">
              {{ book.title }}
            </h3>
          {% endif %}

          {% if book.description %}
            <p class="mb-3 font-normal text-gray-800">
              {{ book.description|truncatechars:200 }}
            </p>
          {% endif %}

          <div class="flex gap-2">
            {% if book.author %}
              <p class="text-gray-800">{{ book.author }}</p>
            {% endif %}

            {% if book.publication_year %}
              <p class="text-gray-800">{{ book.publication_year }}</p>
            {% endif %}
          </div>
        </div>
      </div>
    {% endfor %}
  </div>

{% endblock %}

templates/bookings/gallery.html
{% extends "index.html" %}

  {% block title %}Books{% endblock title %}
  {% block content %}

  <div class="py-8 px-4 w-fit mx-auto">
    <h2 class="text-4xl">Explore our <span class="font-bold">{{category_name}}</span> gallery </h2>
  </div>

  <div class="flex flex-wrap justify-center items-center gap-4 p-8">

    {% for book in books %}
      <div class="flex flex-col bg-white rounded-lg shadow w-full md:flex-row md:max-w-xl hover:bg-zinc-50">

        {% if book.image %}
          <img src="{{ book.image.url }}" class="object-cover w-full rounded-t-lg h-96 md:h-auto md:w-48 md:rounded-none md:rounded-s-lg" alt="">
        {% endif %}

        <div class="flex flex-col justify-between p-4 w-full">

          {% if book.category %}
            <h3 class="font-bold text-gray-900">
              {{ book.category }}
            </h3>
          {% endif %}

          {% if book.title %}
            <h3 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 uppercase">
              {{ book.title }}
            </h3>
          {% endif %}

          {% if book.description %}
            <p class="mb-3 font-normal text-gray-800">
              {{ book.description|truncatechars:200 }}
            </p>
          {% endif %}

          <div class="flex gap-2">
            {% if book.author %}
              <p class="text-gray-800">{{ book.author }}</p>
            {% endif %}

            {% if book.publication_year %}
              <p class="text-gray-800">{{ book.publication_year }}</p>
            {% endif %}
          </div>
        </div>
      </div>
    {% endfor %}

  </div>

{% endblock %}

templates/bookings/gallery_all.html
{% extends "index.html" %}

  {% block title %}Books{% endblock title %}
  {% block content %}

  <section class="bg-white h-full py-6 sm:py-8 lg:py-12">
    <div class="mx-auto max-w-screen-2xl px-4 md:px-8">

      <div class="py-8 px-4 w-fit mx-auto">
        <h2 class="text-4xl">Explore all our gallery </h2>
      </div>

      {% include 'home/gallery_grid.html' %}

    </div>
  </section>

{% endblock%}

templates/global/navbar.html
<!-- Main navigation container -->
<nav class="bg-white border-gray-200">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <a href="https://flowbite.com/" class="flex items-center space-x-3 rtl:space-x-reverse">
      <img src="https://flowbite.com/docs/images/logo.svg" class="h-8" alt="Flowbite Logo" />
      <span class="self-center text-2xl font-semibold whitespace-nowrap">Swift Bookings</span>
    </a>
    <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200" aria-controls="navbar-default" aria-expanded="false">
      <span class="sr-only">Open main menu</span>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
      </svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0 md:bg-white">
        <li>
          <a href="/" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0">Home</a>
        </li>
        <li>
          <a href="/bookings" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0">Books</a>
        </li>
        <li>
          <a href="/bookings/gallery" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0">Gallery</a>
        </li>
        <li>
          <a href="#" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0">Pricing</a>
        </li>
        <li>
          <a href="#" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0">Contact</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<!-- END Main navigation container -->

templates/home/gallery.html
<section class="bg-white h-full py-6 sm:py-8 lg:py-12">
  <div class="mx-auto max-w-screen-2xl px-4 md:px-8">

    <div class="mb-4 flex items-center justify-between gap-8 sm:mb-8 md:mb-12">
      <div class="flex flex-col gap-2">
        <h2 class="text-2xl lg:text-3xl">Gallery</h2>
        <p class="hidden max-w-screen-sm text-gray-800 md:block">Explore the gallery that we have available for you</p>
      </div>
      <a href="#" class="inline-block rounded-lg border border-black px-12 py-3 text-center text-sm md:text-base">More</a>
    </div>

    {% include 'home/gallery_grid.html' %}

  </div>
</section>

templates/home/gallery_grid.html
<div class="grid grid-cols-2 gap-4 sm:grid-cols-3 md:gap-6 xl:gap-8">
  {% for category in categories %}
    <a href="{% url 'bookings:gallery' category=category.name %}" class="group relative flex h-48 items-end overflow-hidden rounded-lg bg-gray-100 shadow-lg md:h-80">

    {% if category.image %}
      <img src="{{ category.image.url }}" loading="lazy" alt="{{ category.name }}" class="absolute inset-0 h-full w-full object-cover object-center transition duration-200 group-hover:scale-110" />
    {% endif %}

    <div class="pointer-events-none absolute inset-0 bg-gradient-to-t from-gray-800 via-transparent to-transparent opacity-50"></div>

    {% if category.name %}
      <span class="relative ml-4 mb-3 inline-block text-sm text-white md:ml-5 md:text-lg">{{ category.name }}</span>
    {% endif %}

    </a>
  {% endfor %}
</div>

templates/home/hero.html
<section class="bg-white py-32 flex flex-col justify-center items-center gap-6">
  <h2 class="text-5xl text-center max-w-4xl">Discover a <span class="text-sky-600">world of adventure</span> through books with our <span class="text-sky-600">rental service</span></h2>
  <div class="flex gap-4">
    <button class="block bg-sky-600 text-white px-12 py-3 rounded-md">Get started</button>
    <button class="block border text-sky-600 border-sky-600 px-12 py-3 rounded-md">Learn more</button>
  </div>
</section>

templates/home/home.html
{% extends 'index.html' %}

  {% block content %}
  {% include "home/hero.html" %}
  {% include "home/gallery.html" %}

{% endblock %}

templates/index.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    {% tailwind_css %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>
    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>

    {% include 'global/navbar.html' %}

    {% block content %}
    {% endblock %}

  </body>
</html>

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>